# You can raise exceptions by using the raise statement.
print(1)
raise ValueError
print(2)

# Result:
"""
1
ValueError
"""
